# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pro/pro.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro || ORIG_REF_NAME==pro} -quiet] -quiet

# IP: bd/pro/ip/pro_processing_system7_0_0/pro_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro_processing_system7_0_0 || ORIG_REF_NAME==pro_processing_system7_0_0} -quiet] -quiet

# IP: bd/pro/ip/pro_axi_dma_0_1/pro_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro_axi_dma_0_1 || ORIG_REF_NAME==pro_axi_dma_0_1} -quiet] -quiet

# IP: bd/pro/ip/pro_xfft_0_0/pro_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro_xfft_0_0 || ORIG_REF_NAME==pro_xfft_0_0} -quiet] -quiet

# IP: bd/pro/ip/pro_axi_smc_0/pro_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro_axi_smc_0 || ORIG_REF_NAME==pro_axi_smc_0} -quiet] -quiet

# IP: bd/pro/ip/pro_rst_ps7_0_100M_0/pro_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro_rst_ps7_0_100M_0 || ORIG_REF_NAME==pro_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pro/ip/pro_ps7_0_axi_periph_0/pro_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro_ps7_0_axi_periph_0 || ORIG_REF_NAME==pro_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pro/ip/pro_xlconstant_0_0/pro_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro_xlconstant_0_0 || ORIG_REF_NAME==pro_xlconstant_0_0} -quiet] -quiet

# IP: bd/pro/ip/pro_xlconstant_1_0/pro_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro_xlconstant_1_0 || ORIG_REF_NAME==pro_xlconstant_1_0} -quiet] -quiet

# IP: bd/pro/ip/pro_auto_pc_0/pro_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pro_auto_pc_0 || ORIG_REF_NAME==pro_auto_pc_0} -quiet] -quiet

# XDC: bd/pro/pro_ooc.xdc
