set_property SRC_FILE_INFO {cfile:/home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_processing_system7_0_0/pl_processing_system7_0_0.xdc rfile:../../../../../CW_11_fft.srcs/sources_1/bd/pl/ip/pl_processing_system7_0_0/pl_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.runs/pl_processing_system7_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_fpga_0 [get_pins {PS7_i/FCLKCLK[0]}]
current_instance
set_property src_info {type:SCOPED_XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {MIO[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {MIO[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {MIO[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {MIO[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {MIO[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {MIO[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {MIO[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {MIO[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {MIO[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {MIO[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {MIO[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {MIO[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {MIO[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {MIO[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {MIO[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {MIO[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {MIO[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {MIO[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {MIO[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {MIO[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {MIO[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {MIO[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {MIO[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {MIO[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {MIO[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {MIO[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {MIO[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {MIO[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {MIO[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {MIO[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {MIO[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {MIO[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports DDR_VRP]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_VRP]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports DDR_VRP]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports DDR_VRN]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_VRN]
set_property src_info {type:SCOPED_XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports DDR_VRN]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_WEB]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_WEB]
set_property src_info {type:SCOPED_XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_WEB]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_RAS_n]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_RAS_n]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_RAS_n]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_ODT]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_ODT]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_ODT]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_DRSTB]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_DRSTB]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports DDR_DRSTB]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_DQS[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQS[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQS[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_DQS[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQS[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQS[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_DQS[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQS[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQS[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_DQS[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQS[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQS[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_DQS_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQS_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQS_n[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_DQS_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQS_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQS_n[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_DQS_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQS_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQS_n[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_DQS_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQS_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQS_n[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DQ[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DQ[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DQ[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DM[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DM[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DM[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DM[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DM[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DM[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DM[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DM[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DM[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_DM[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_DM[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_DM[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_CS_n]
set_property src_info {type:SCOPED_XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_CS_n]
set_property src_info {type:SCOPED_XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_CS_n]
set_property src_info {type:SCOPED_XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_CKE]
set_property src_info {type:SCOPED_XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_CKE]
set_property src_info {type:SCOPED_XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_CKE]
set_property src_info {type:SCOPED_XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_Clk]
set_property src_info {type:SCOPED_XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_Clk]
set_property src_info {type:SCOPED_XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports DDR_Clk]
set_property src_info {type:SCOPED_XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_Clk_n]
set_property src_info {type:SCOPED_XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_Clk_n]
set_property src_info {type:SCOPED_XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports DDR_Clk_n]
set_property src_info {type:SCOPED_XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_CAS_n]
set_property src_info {type:SCOPED_XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_CAS_n]
set_property src_info {type:SCOPED_XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_CAS_n]
set_property src_info {type:SCOPED_XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_BankAddr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_BankAddr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_BankAddr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_BankAddr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_BankAddr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_BankAddr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_BankAddr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_BankAddr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_BankAddr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_Addr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_Addr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_Addr[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PS_PORB]
set_property src_info {type:SCOPED_XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports PS_PORB]
set_property src_info {type:SCOPED_XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports PS_SRSTB]
set_property src_info {type:SCOPED_XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports PS_SRSTB]
set_property src_info {type:SCOPED_XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PS_CLK]
set_property src_info {type:SCOPED_XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports PS_CLK]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells inst]
