# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pl/pl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl || ORIG_REF_NAME==pl} -quiet] -quiet

# IP: bd/pl/ip/pl_processing_system7_0_0/pl_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_processing_system7_0_0 || ORIG_REF_NAME==pl_processing_system7_0_0} -quiet] -quiet

# IP: bd/pl/ip/pl_xfft_0_0/pl_xfft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_xfft_0_0 || ORIG_REF_NAME==pl_xfft_0_0} -quiet] -quiet

# IP: bd/pl/ip/pl_axis_dwidth_converter_0_0/pl_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_axis_dwidth_converter_0_0 || ORIG_REF_NAME==pl_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/pl/ip/pl_floating_point_0_0/pl_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_floating_point_0_0 || ORIG_REF_NAME==pl_floating_point_0_0} -quiet] -quiet

# IP: bd/pl/ip/pl_axi_dma_0_0/pl_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_axi_dma_0_0 || ORIG_REF_NAME==pl_axi_dma_0_0} -quiet] -quiet

# IP: bd/pl/ip/pl_axi_smc_0/pl_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_axi_smc_0 || ORIG_REF_NAME==pl_axi_smc_0} -quiet] -quiet

# IP: bd/pl/ip/pl_rst_ps7_0_100M_0/pl_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_rst_ps7_0_100M_0 || ORIG_REF_NAME==pl_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pl/ip/pl_auto_pc_0/pl_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_auto_pc_0 || ORIG_REF_NAME==pl_auto_pc_0} -quiet] -quiet

# IP: bd/pl/ip/pl_ps7_0_axi_periph_0/pl_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_ps7_0_axi_periph_0 || ORIG_REF_NAME==pl_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pl/ip/pl_xlconstant_0_0/pl_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_xlconstant_0_0 || ORIG_REF_NAME==pl_xlconstant_0_0} -quiet] -quiet

# IP: bd/pl/ip/pl_xlconstant_1_0/pl_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_xlconstant_1_0 || ORIG_REF_NAME==pl_xlconstant_1_0} -quiet] -quiet

# IP: bd/pl/ip/pl_system_ila_0_0/pl_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_system_ila_0_0 || ORIG_REF_NAME==pl_system_ila_0_0} -quiet] -quiet

# XDC: bd/pl/pl_ooc.xdc
