# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vs/funtion/verilog/ELD_LAB/HW6_AXI_equation/HW6_AXI_equation.srcs/sources_1/ip/fp_log/fp_log.xci
# IP: The module: 'fp_log' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW6_AXI_equation/HW6_AXI_equation.srcs/sources_1/ip/fp_log/fp_log_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_log'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/vs/funtion/verilog/ELD_LAB/HW6_AXI_equation/HW6_AXI_equation.srcs/sources_1/ip/fp_log/fp_log.xci
# IP: The module: 'fp_log' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW6_AXI_equation/HW6_AXI_equation.srcs/sources_1/ip/fp_log/fp_log_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_log'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
