# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vs/funtion/verilog/ELD_LAB/HW8.1_try2/HW8.1_try2.srcs/sources_1/bd/test/ip/test_processing_system7_0_0/test_processing_system7_0_0.xci
# IP: The module: 'test_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW8.1_try2/HW8.1_try2.srcs/sources_1/bd/test/ip/test_processing_system7_0_0/test_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/vs/funtion/verilog/ELD_LAB/HW8.1_try2/HW8.1_try2.srcs/sources_1/bd/test/ip/test_processing_system7_0_0/test_processing_system7_0_0.xci
# IP: The module: 'test_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW8.1_try2/HW8.1_try2.srcs/sources_1/bd/test/ip/test_processing_system7_0_0/test_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
