# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zed_cf.xdc

# IP: ip/vio_fa/vio_fa.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_fa || ORIG_REF_NAME==vio_fa} -quiet] -quiet

# XDC: /home/vs/funtion/verilog/ELD_LAB/LAB2_hardware_adder-L1/LAB2_hardware_adder-L1.gen/sources_1/ip/vio_fa/vio_fa.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_fa || ORIG_REF_NAME==vio_fa} -quiet] -quiet
