# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vs/funtion/verilog/ELD_LAB/HW10_FFT_FPGA+ARM/HW10_FFT_FPGA+ARM.srcs/sources_1/bd/pro/ip/pro_axi_dma_0_1/pro_axi_dma_0_1.xci
# IP: The module: 'pro_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW10_FFT_FPGA+ARM/HW10_FFT_FPGA+ARM.srcs/sources_1/bd/pro/ip/pro_axi_dma_0_1/pro_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pro_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW10_FFT_FPGA+ARM/HW10_FFT_FPGA+ARM.srcs/sources_1/bd/pro/ip/pro_axi_dma_0_1/pro_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pro_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW10_FFT_FPGA+ARM/HW10_FFT_FPGA+ARM.srcs/sources_1/bd/pro/ip/pro_axi_dma_0_1/pro_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pro_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/vs/funtion/verilog/ELD_LAB/HW10_FFT_FPGA+ARM/HW10_FFT_FPGA+ARM.srcs/sources_1/bd/pro/ip/pro_axi_dma_0_1/pro_axi_dma_0_1.xci
# IP: The module: 'pro_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW10_FFT_FPGA+ARM/HW10_FFT_FPGA+ARM.srcs/sources_1/bd/pro/ip/pro_axi_dma_0_1/pro_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'pro_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW10_FFT_FPGA+ARM/HW10_FFT_FPGA+ARM.srcs/sources_1/bd/pro/ip/pro_axi_dma_0_1/pro_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pro_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW10_FFT_FPGA+ARM/HW10_FFT_FPGA+ARM.srcs/sources_1/bd/pro/ip/pro_axi_dma_0_1/pro_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pro_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
