# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_auto_pc_0/pl_auto_pc_0.xci
# IP: The module: 'pl_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_auto_pc_0/pl_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pl_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_auto_pc_0/pl_auto_pc_0.xci
# IP: The module: 'pl_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_auto_pc_0/pl_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pl_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
