# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-160135-buntu/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/1ddd/hdl/verilog
    /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/b2d0/hdl/verilog
  } {
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/1ddd/hdl/sc_util_v1_0_vl_rfs.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_2/synth/bd_7b35_arsw_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_3/synth/bd_7b35_rsw_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_4/synth/bd_7b35_awsw_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_5/synth/bd_7b35_wsw_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_6/synth/bd_7b35_bsw_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_7/synth/bd_7b35_s00mmu_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_8/synth/bd_7b35_s00tr_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/7de4/hdl/sc_si_converter_v1_0_vl_rfs.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_9/synth/bd_7b35_s00sic_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_10/synth/bd_7b35_s00a2s_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_11/synth/bd_7b35_sarn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_12/synth/bd_7b35_srn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_13/synth/bd_7b35_s01mmu_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_14/synth/bd_7b35_s01tr_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_15/synth/bd_7b35_s01sic_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_16/synth/bd_7b35_s01a2s_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_17/synth/bd_7b35_sawn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_18/synth/bd_7b35_swn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_19/synth/bd_7b35_sbn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_20/synth/bd_7b35_m00s2a_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_21/synth/bd_7b35_m00arn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_22/synth/bd_7b35_m00rn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_23/synth/bd_7b35_m00awn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_24/synth/bd_7b35_m00wn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_25/synth/bd_7b35_m00bn_0.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_26/synth/bd_7b35_m00e_0.sv
      /tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/1ddd/hdl/verilog
    /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/b2d0/hdl/verilog
  } {
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/synth/pl_axi_smc_0.v
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_0/synth/bd_7b35_one_0.v
      /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/synth/bd_7b35.v
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib /home/vs/funtion/verilog/ELD_LAB/CW_11_fft/CW_11_fft.srcs/sources_1/bd/pl/ip/pl_axi_smc_0/bd_0/ip/ip_1/synth/bd_7b35_psr_aclk_0.vhd
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top pl_axi_smc_0
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-160135-buntu/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
