# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/vs/funtion/verilog/ELD_LAB/HW7.2_AXI_f_-x-y-z/HW7.2_AXI_f_-x-y-z.srcs/sources_1/ip/add/add.xci
# IP: The module: 'add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW7.2_AXI_f_-x-y-z/HW7.2_AXI_f_-x-y-z.srcs/sources_1/ip/add/add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/vs/funtion/verilog/ELD_LAB/HW7.2_AXI_f_-x-y-z/HW7.2_AXI_f_-x-y-z.srcs/sources_1/ip/add/add.xci
# IP: The module: 'add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/vs/funtion/verilog/ELD_LAB/HW7.2_AXI_f_-x-y-z/HW7.2_AXI_f_-x-y-z.srcs/sources_1/ip/add/add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
